# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, inputs, lib, pkgs, modulesPath, ... }:
let
  officialKernelNames =
    builtins.filter
    (name: builtins.match "^linux(_[0-9]+_[0-9]+|_latest)?$" name != null)
    (builtins.attrNames pkgs.linuxKernel.kernels);

  officialStableKernels =
    builtins.filter (kernel: kernel != null) (
      map (
        name:
          let
            attempt = builtins.tryEval pkgs.linuxKernel.kernels.${name};
          in
          if attempt.success && !(lib.hasInfix "-rc" attempt.value.version)
          then attempt.value
          else null
      )
      officialKernelNames
    );

  latestOfficialStableKernel =
    builtins.elemAt
    (lib.sort (a: b: lib.versionOlder a.version b.version) officialStableKernels)
    ((builtins.length officialStableKernels) - 1);
in {
  imports =
    [ inputs.lanzaboote.nixosModules.lanzaboote
      (modulesPath + "/hardware/cpu/intel-npu.nix")
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  assertions = [
    {
      assertion = builtins.length officialStableKernels > 0;
      message = "hosts/xps-v could not find an official stable kernel in the current nixpkgs pin.";
    }
    {
      assertion = !(lib.hasInfix "-rc" latestOfficialStableKernel.version);
      message = "hosts/xps-v must track the latest stable kernel only; resolved kernel version `${latestOfficialStableKernel.version}` is a release candidate.";
    }
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  # Track the newest official stable kernel available in the current nixpkgs pin.
  boot.kernelPackages = lib.mkForce (pkgs.linuxPackagesFor latestOfficialStableKernel);
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.loader.systemd-boot.enable = lib.mkForce false;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.lanzaboote = {
    enable = true;
    pkiBundle = "/var/lib/sbctl";
    configurationLimit = 5;
    settings = {
      timeout = 5;
      editor = "no";
      default = "@saved";
    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c2ba8738-fd93-4089-9205-fe8a1809b128";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4694-892E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];
  zramSwap = {
    enable = true;
    memoryPercent = 25;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  services.thermald.enable = true;
  services.fwupd.enable = true;
  services.hardware.bolt.enable = true;
  # Goodix 27c6:633c enumerates, but support is not confirmed locally yet.
}
